export const initialShowcaseState = {
  hasContainer: true,
  color: "rgba(255,255,255,0)",
  gridNumber: { id: 7, title: "4/4" },
  active: false,
  showCaseLimit: 7,
  showTitle: true,
  gridGap: 10,
  gridGapMobile: 10,
  column: 2,
  columnMobile: 1,
  paddingY: 10,
  paddingX: 0,
  borderRaduis: 0,
  borderWidth: 0,
  carouselNumber: 5,
  titlePosition: { id: 1, title: "right" },
  moreLink: "/",
  shadow: "rgba(255,255,255,0)",
  // Desktop settings
  marginTop: 5,
  marginBottom: 5,
  paddingTop: 15,
  paddingBottom: 15,
  paddingLeft: 0,
  paddingRight: 0,
  sectionBorderTop: 0,
  sectionBorderRight: 0,
  sectionBorderBottom: 0,
  sectionBorderLeft: 0,
  borderSectionRaduisTop: 12,
  borderSectionRaduisRight: 12,
  borderSectionRaduisBottom: 12,
  borderSectionRaduisLeft: 12,
  elementBorderTop: 0,
  elementBorderRight: 0,
  elementBorderBottom: 0,
  elementBorderLeft: 0,
  borderElementRaduisTop: 12,
  borderElementRaduisRight: 12,
  borderElementRaduisBottom: 12,
  borderElementRaduisLeft: 12,
  // Mobile settings
  paddingTopMobile: 5,
  paddingBottomMobile: 5,
  paddingLeftMobile: 0,
  paddingRightMobile: 0,
  sectionBorderTopMobile: 0,
  sectionBorderRightMobile: 0,
  sectionBorderBottomMobile: 0,
  sectionBorderLeftMobile: 0,
  borderSectionRaduisTopMobile: 8,
  borderSectionRaduisRightMobile: 8,
  borderSectionRaduisBottomMobile: 8,
  borderSectionRaduisLeftMobile: 8,
  elementBorderTopMobile: 0,
  elementBorderRightMobile: 0,
  elementBorderBottomMobile: 0,
  elementBorderLeftMobile: 0,
  borderElementRaduisTopMobile: 8,
  borderElementRaduisRightMobile: 8,
  borderElementRaduisBottomMobile: 8,
  borderElementRaduisLeftMobile: 8,
  marginTopMobile: 2,
  marginBottomMobile: 2,
  // Story and promotion settings
  storyLength: 3,
  counterColor: "#fff",
  promotionBg: "#FFA94D",
  showPrice: true,
  showDelivery: true,
  tomanIcon: true,
  showOldPrice: true,
  showPrecent: true,
  showScore: true,
  showColor: true,
  showProductTitle: true,
  showImg: true,
  showCounter: true,
  showPromotionIcon: true,
  borderBottomPromotion: true,
  borderBottomPromotionColor: "#FFA94D",
  showPromotion: true,
};

export const initialBackgroundSettings = {
  possitionY: "center",
  possitionX: "center",
  size: "cover",
  opacity: 100,
};

export const SHOWCASE_STEPS = ["تعریف ویترین", "تنظیمات پس زمینه", " انتخاب محتوا"];
