/**
 * Centralized API Routes for Page Configurations
 * This file exports all API route constants used across page configurations
 */

export {
  // Brands
  BRANDS,
  EXPORT_BRANDS,
  CREATE_BRAND,
  EDIT_BRAND,
  EDIT_ACTIVE_BRAND,
  DELETE_BRAND,
  
  // Categories  
  CATEGORIES,
  EXPORT_CATEGORIES,
  CREATE_CATEGORY,
  EDIT_CATEGORY,
  EDIT_ACTIVE_CATEGORY,
  DELETE_CATEGORY,
  
  // Attributes
  ATTRIBUTES,
  EXPORT_ATTRIBUTES,
  CREATE_ATTR,
  EDIT_ATTR,
  EDIT_ACTIVE_ATTR,
  DELETE_ATTR,
  
  // Public Attributes
  PUBLIC_ATTRS,
  EXPORT_PUBLIC_ATTRS,
  CREATE_PUBLIC_ATTR,
  EDIT_PUBLIC_ATTR,
  EDIT_ACTIVE_PUBLIC_ATTR,
  DELETE_PUBLIC_ATTR,
  
  // Attribute Groups
  ATTR_GROUPS,
  EXPORT_ATTR_GROUPS,
  CREATE_ATTR_GROUP,
  EDIT_ATTR_GROUP,
  EDIT_ACTIVE_ATTR_GROUP,
  DELETE_ATTR_GROUP,
  
  // Info Groups (Category Abilities)
  ALL_INFOGROUPS,
  EXPORT_ALL_INFOGROUPS,
  CREATE_INFOGROUP,
  EDIT_INFOGROUP,
  EDIT_ACTIVE_INFOGROUP,
  DELETE_INFOGROUP,
  
  // Report APIs
  GET_RESERVE_REPORT,
  EXPORT_RESERVE_REPORT,
  GET_INVOICE_REPORT,
  EXPORT_INVOICE_REPORT,
  GET_LOG_REPORT,
  EXPORT_LOG_REPORT,
  GET_PLAN_REPORT,
  EXPORT_PLAN_REPORT,
  GET_REPORT_TRANSACTION,
  EXPORT_REPORT_TRANSACTION,
  GET_SHIPMENT_REPORT,
  EXPORT_SHIPMENT_REPORT,
  GET_DISCOUNT_REPORT,
  EXPORT_DISCOUNT_REPORT,
  GET_REFERRAL_REPORT,
  EXPORT_REFERRAL_REPORT,
  GET_REPORT_LOAN_USER,
  EXPORT_REPORT_LOAN_USER,
  GET_REPORT_LOAN_AGENT,
  EXPORT_REPORT_LOAN_AGENT,
  GET_REPORT_DEPOT,
  EXPORT_REPORT_DEPOT,
  GET_ReportFinancierInstallment,
  EXPORT_ReportFinancierInstallment,
  GET_REPORT_SINGLE_LOAN,
  EXPORT_REPORT_SINGLE_LOAN,
  GET_SUM_GATEWAY_BY_USER,
  EXPORT_SUM_GATEWAY_BY_USER,
  ALL_REPORT_SHIPPING_COST,
  EXPORT_REPORT_SHIPPING_COST,
  
  // Complex Report APIs
  GET_DAILY_REPORT,
  EXPORT_DAILY_REPORT,
  GET_SUM_INVOICE_DAILY,
  GET_SUM_GATEWAY,
  EXPORT_SUM_GATEWAY,
  GET_SUM_GATEWAY_ALL,
  GET_PAYMENT_LOG,
  EXPORT_PAYMENT_LOG,
  DELETE_PAYMENT_LOG,
  DELETE_ALL_PAYMENT_LOG,
  DELETE_MONTH_PAYMENT_LOG,
  GET_REPORT_WALLET_BALANCE,
  EXPORT_REPORT_WALLET_BALANCE,
  TOGGLE_WALLET_BALANCE,
  GET_PLAN_LANDING_REPORT,
  EXPORT_PLAN_LANDING_REPORT,
  REJECT_PLAN_LANDING_REPORT,
  APPROVED_PLAN_LANDING_REPORT,
  GET_FACILITY_REPORT_WALLET_BALANCE,
  EXPORT_FACILITY_REPORT_WALLET_BALANCE,
  GET_ReportOverdueInstallmentsBasedOnFinancier,
  EXPORT_ReportOverdueInstallmentsBasedOnFinancier,
  GET_AGENT_SUMMERY,
  EXPORT_AGENT_SUMMERY,
  GET_USER_FACILITY_TURN_OVER,
  EXPORT_USER_FACILITY_TURN_OVER,
} from '../../helpers/api-routes'; 